### ISSUE TITLE
bug: Zero-ui is not compatible with the Microsoft Edge browser

### ISSUE THREAD

**Issue by youtehub** [dec0dOS/zero-ui#108]
# Bug Report

**ZeroUI version:**

v1.5.1

latest

**Current behavior:**

When I used Docker Compose to deploy Zero-UI on Ubuntu this afternoon, the whiteboard appeared when I opened the page of the app using the Edge browser, as shown in the figure.When opened with Chrome and Firefox, it is normal. The problem only appeared after the V1.5.1 update, which started showing up around noon today
![image](https://user-images.githubusercontent.com/18629921/186903730-4ef6bd65-3a34-4c06-b459-3cc9ebcd7e0e.png)

**Expected behavior:**

I hope the later module can be compatible with Microsoft Edge browser, this browser is the default browser of Windows, it is quite useful, I hope it can be compatible with this browser, after all, the mainstream browsers now are Firefox, Edge, Chrome.
Some people mentioned this issue in the discussion group, mainly because the latest version of the browser compatibility issues, so I will raise an issue here

**Steps to reproduce:**

I'm using Ubuntu to load the latest docker, Docker Compose, Then use the installation method mentioned in the document To download Docker-compose. Yml,To disable Caddy proxy and HTTPS, remove the http-proxy from Docker-compose. set ZU_SECURE_HEADERS to false and change zero-ui port expose to ports.

Then deploy it into Docker as follows. When accessed on Edge browser, whiteboard appears. V1.5.1 released on the morning of August 26, 2022, has this problem when Docker is deployed.

Now, I'm using the Settings page on Chrome or Firefox, setting things up, and yesterday it was all accessible on the Edge browser

**Comment by dec0dOS** [comment]
Hello, @youtehub.
I think that it is not really related to the specific browser. Clean the Edge cache files and data, it should be fine.

**Comment by dec0dOS** [comment]
By the way, there is no such v1.5.1 version.
![Screenshot 2022-08-26 at 15 50 00](https://user-images.githubusercontent.com/14824142/186907167-f18ea850-af1d-47b8-acac-f7cad6a7d84b.png)

**Comment by dec0dOS** [comment]
If the related problem does not solve, check the browser console page. It is impossible to determine what the problem is without any logs.

**Comment by dec0dOS** [comment]
ZeroUI works fine in Edge on Windows 11

**Comment by youtehub** [comment]
thanks, Clean the Edge cache files and data, it works normally.

**Comment by youtehub** [comment]
thanks, Clean the Edge cache files and data, it works normally.
