### ISSUE TITLE
bug: No such file or directory: 'install'

### ISSUE THREAD

**Issue by republicus** [dec0dOS/zero-ui#111]
# Bug Report

**ZeroUI version:**

latest

**Current behavior:**

Attempting to install development environment fails

```

root@zeroteir:~/zero-ui# yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

root@zeroteir:~/zero-ui# ls
CHANGELOG.md  README.md  docker              docs      package.json
LICENSE       backend    docker-compose.yml  frontend  yarn.lock

```

**Steps to reproduce:**
```

git clone https://github.com/dec0dOS/zero-ui.git
cd zero-ui
yarn install

```

**Other information:**

I didn't see any information for installation without docker, which I do not intend to use.  I have installed *zerotier-one* on my linux host and proceeded to install *zero-ui* development environment. Is the development environment intended to install on-top of the docker container? Do instructions for installation on bare-metal environments exist?

**Comment by dec0dOS** [comment]
Hello, @republicus. Something is wrong with your nodejs/yarn installation. Please try to install the latest yarn version (v3)

**Comment by republicus** [comment]
Thanks, nodejs and yarn were updated with npm. distro provided yarn wouldn't even give me version info without a very similar error.
