### ISSUE TITLE
How to reset password?

### ISSUE THREAD

**Issue by roxlu** [dec0dOS/zero-ui#113]
I've been using zero-ui as a self-hosted service, without docker. I want to change the password of ZT_DEFAULT_PASSWORD. After changing the password I couldn't login anymore. I noticed that in data/db.json there is an entry of my username with a hashed password; I'm not sure if this hashed password might contain the old password?

Thanks!

**Comment by dec0dOS** [comment]
Hello, @roxlu.
Check the https://github.com/dec0dOS/zero-ui/discussions/16
