### ISSUE TITLE
Creating network always got 404 from controller.

### ISSUE THREAD

**Issue by sbilly** [dec0dOS/zero-ui#15]
The  function `getNetworksData()` in `backend/services/network.js` always got 404 from controller.

https://github.com/dec0dOS/zero-ui/blob/cfdddd1dd60e2990cfd578f32dd12a006ff93795/backend/services/network.js#L39

**Comment by sbilly** [comment]
Creating network, got the 200 response with networkId `a4de2130c2b2f7db`.

![image](https://user-images.githubusercontent.com/123563/132336240-e5fd54b1-1511-4ea8-a57c-cda42a464d98.png)

Get the network `a4de2130c2b2f7db` information, but got 404 response from controller.

![image](https://user-images.githubusercontent.com/123563/132336415-79e1730c-335c-4fd2-9628-f62c4eb163a9.png)

I've tried many times, and got the same result.

![image](https://user-images.githubusercontent.com/123563/132336142-4b10b890-250f-4535-9d6e-790a91178c7b.png)

**Comment by dec0dOS** [comment]
Hello, @sbilly. Thanks for your contribution, I've seen that you are using the [custom ZeroTier setup](https://github.com/sbilly/docker-zerotier-controller). It is really hard to guess what is wrong with this kind of setup.

Please check the official ZeroUI docker-compose configuration and let me know if it works for you. I don't have any problems with the latest ZeroUI build.

**Comment by sbilly** [comment]
I'm testing zerotier controller with pgsql, which is not supported in ZeroUI docker-compose.

**Comment by dec0dOS** [comment]
I'm sorry, I could not provide any support for a such configuration. The problem could be related to zerotier controller, but not the ZeroUI.

**Comment by sbilly** [comment]
It's works fine when I using curl to create network with `X-ZT1-Auth` token.

```bash
curl -H 'X-ZT1-Auth: uv5mju4vfraxap4a46gp0f5l' http://127.0.0.1:8883/controller/network/`curl -H 'X-ZT1-Auth: uv5mju4vfraxap4a46gp0f5l' http://127.0.0.1:8883/controller/network/a4de2130c2______  -X POST -d '{"name":"new-net-64090","private":true,"v6AssignMode":{"rfc4193":false,"6plane":false,"zt":false},"v4AssignMode":{"zt":true},"routes":[{"target":"172.30.236.0/24","via":null,"flags":0,"metric":0}],"ipAssignmentPools":[{"ipRangeStart":"172.30.236.1","ipRangeEnd":"172.30.236.254"}],"enableBroadcast":true,"rules":[{"type":"MATCH_ETHERTYPE","not":true,"or":false,"etherType":2048},{"type":"MATCH_ETHERTYPE","not":true,"or":false,"etherType":2054},{"type":"MATCH_ETHERTYPE","not":true,"or":false,"etherType":34525},{"type":"ACTION_DROP"},{"type":"ACTION_ACCEPT"}]}' -s | jq -r ".id"`
```

**Comment by dec0dOS** [comment]
You're calling the controller API directly, but not through the ZeroUI backend. You should not expose the controller API.
