### ISSUE TITLE
bug: Zero UI does not work when using host-path for controller 

### ISSUE THREAD

**Issue by projx** [dec0dOS/zero-ui#17]
# Bug Report

**ZeroUI version:**

latest

**Current behavior:**

When using a standard docker volume everything works fine, but if I use a host-path (i.e. /data/my_docker_data) volume for the zerotier controller, the zero-ui crashes and exits with the error below.  This is fairly bizarre, I've used Docker for several years and never experienced this, I've ensured the Host directory has the correct permissions and ownership (matching exactly the same as when utilising a docker-volume), another note, I don't experience this issue ZTBCUI's controller:

```
zu-main exited with code 1
zu-main     | node:internal/errors:691
zu-main     |   const ex = new Error(msg);
zu-main     |              ^
zu-main     |
zu-main     | Error: socket hang up
zu-main     |     at connResetException (node:internal/errors:691:14)
zu-main     |     at Socket.socketOnEnd (node:_http_client:471:23)
zu-main     |     at Socket.emit (node:events:406:35)
zu-main     |     at endReadableNT (node:internal/streams/readable:1348:12)
zu-main     |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
zu-main     |   code: 'ECONNRESET',
zu-main     |   config: {
zu-main     |     url: 'status',
zu-main     |     method: 'get',
zu-main     |     headers: {
zu-main     |       Accept: 'application/json, text/plain, */*',
zu-main     |       'X-ZT1-Auth': 'edi9jjcrk2j2l9thozezbf71',
zu-main     |       'User-Agent': 'axios/0.21.1'
```

Running the following docker compose:

```
version: "3.9"

services:

  zerotier:
    image: dec0dos/zerotier-controller:latest
    container_name: zu-controller

    restart: unless-stopped
    volumes:
      - '/data/controller/:/var/lib/zerotier-one'
      #- controller_data:/var/lib/zerotier-one
    expose:
      - "9993/tcp"
    ports:
      - "9993:9993/udp"


  zero-ui:
    image: dec0dos/zero-ui:latest
    container_name: zu-main
    # build:
    #   context: .
    #   dockerfile: ./docker/zero-ui/Dockerfile
    restart: unless-stopped
    depends_on:
      - zerotier
    volumes:
      - '/data/controller/:/var/lib/zerotier-one'
      #- controller_data:/var/lib/zerotier-one
      - /cntrs/data/zero-ui/zero-ui:/app/backend/data
    environment:
      - ZU_CONTROLLER_ENDPOINT=http://zerotier:9993/
      - ZU_SECURE_HEADERS=false
      - ZU_DEFAULT_USERNAME=admin
      - ZU_DEFAULT_PASSWORD=zero-ui
    expose:
      - "4000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.zt_https.rule=Host(`zt.prjx.uk`)
      - traefik.http.routers.zt_https.entrypoints=websecure
      - traefik.http.routers.zt_https.tls=true
      - traefik.http.services.zt_https.loadbalancer.server.port=4000
    expose:
      - "4000"


volumes:
  zero-ui_data:
  controller_data:
  caddy_data:
```

**Expected behavior:**

When using a docker-volume, it does not generate this error and the UI works as expected.

**Steps to reproduce:**

Use the above docker-compose.yml .. Not you can remove the Traefik config... the issue still occurs.

**Comment by dec0dOS** [comment]
Hello, @projx! Hmm, that is strange. It seems that ZeroTier controller crashes in docker, so the ZeroUI could not connect to the controller. Please check the controller API manually. It may be also the problem with the permissions, there are some special permissions for `/var/lib/zerotier-one/authtoken.secret` file. You could try getting the auth token and setting the ZU_CONTROLLER_TOKEN variable.

**Comment by Schu-** [comment]
Hi! So this is a neat project and so far is working well in my test environment. I just wanted to add to this bug. I have also found this to be the case. If you changed it to the host path it fails and does not work. I did however find a workaround that worked so far for me. If you keep it as a volume, but define the volume with the host path, that seems to work. Here is my docker compose file (disregard the mcvlan network attached to the containers):

docker-compose.yml
`version: "3.9"

services:
  zerotier:
    image: dec0dos/zerotier-controller:latest
    container_name: zt-controller
    build:
      context: .
      dockerfile: ./docker/zerotier/Dockerfile
    restart: unless-stopped
    volumes:
      - zt-controller:/var/lib/zerotier-one
    expose:
      - "9993/tcp"
    ports:
      - "9993:9993/udp"
    networks:
            docker:
                ipv4_address: XXX.XX.XXX.XXX
  zero-ui:
    image: dec0dos/zero-ui:latest
    container_name: zt-ui
    build:
      context: .
      dockerfile: ./docker/zero-ui/Dockerfile
    restart: unless-stopped
    depends_on:
      - zerotier
    volumes:
      - zt-controller:/var/lib/zerotier-one
      - zt-ui:/app/backend/data
    environment:
      - ZU_CONTROLLER_ENDPOINT=http://zerotier:9993/
      - ZU_SECURE_HEADERS=true
      - ZU_DEFAULT_USERNAME=admin
      - ZU_DEFAULT_PASSWORD=zero-ui
    expose:
      - "4000"
    networks:
            docker:
                ipv4_address: XXX.XXX.XXX.XXX
volumes:
  zt-controller:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/docker/zt-controller/config'
  zt-ui:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/docker/zt-ui/config'
networks:
 docker:
  external: true`

Hope this helps anyone with this issue.

-Andrew

**Comment by dec0dOS** [comment]
Hello, @Schu-!

Thanks for sharing, that is really helpful!
