### ISSUE TITLE
feat: implement rate-limiting for authorization

### ISSUE THREAD

**Issue by dec0dOS** [dec0dOS/zero-ui#175]
# Feature Request

**Additional Context**

More info here:
https://github.com/dec0dOS/zero-ui/security/code-scanning/5

**Comment by aruznieto** [comment]
Link doesnt work

**Comment by dec0dOS** [comment]
Seems like code scanning alerts are available only for maintainers. Here's the extracted data from the link:
[Missing rate limiting · Code scanning alert #5 · dec0dOS:zero-ui.pdf](https://github.com/dec0dOS/zero-ui/files/12894678/Missing.rate.limiting.Code.scanning.alert.5.dec0dOS.zero-ui.pdf)

**Comment by aruznieto** [comment]
WIP

**Comment by dec0dOS** [comment]
Closed with https://github.com/dec0dOS/zero-ui/pull/179. Thanks, @aruznieto!

**Comment by dec0dOS** [comment]
Some issues with the rate limiter:
https://github.com/dec0dOS/zero-ui/discussions/181#discussioncomment-7294898

**Comment by dec0dOS** [comment]
Fixed with https://github.com/dec0dOS/zero-ui/commit/213c9499f2cabda1706225750f40dab64d5297a0
