### ISSUE TITLE
bug: The new version does not open 4000 ports ？

### ISSUE THREAD

**Issue by v808comd** [dec0dOS/zero-ui#176]
![image](https://github.com/dec0dOS/zero-ui/assets/65583931/dc97c96f-df1f-40f3-a24c-e9523bd98a3e)

**Comment by aruznieto** [comment]
Are you using the docker-compose.yml file of the repo and using https-proxy? If you comment https-proxy section you must to change
```
expose:
      - "4000"
```

to 

```
ports:
      - "4000:4000"
```

**Comment by v808comd** [comment]
Thank you very much. This problem has been resolved.
I did not use https proxy. Because it has not been used successfully.

Now use it directly http://ip:4000 Come to visit, but the open page is a blank page.
My Docker Compose.yml file is as follows:

version: "3"

services:
  zerotier:
    image: zyclonite/zerotier:1.10.6
    container_name: zu-controller
    restart: unless-stopped
    volumes:
      - ./zerotier-one:/var/lib/zerotier-one
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=0.0.0.0/0
    expose:
      - "9993/tcp"
    ports:
      - "9993:9993/udp"
  zero-ui:
    image: dec0dos/zero-ui:latest
    container_name: zu-main
    build:
      context: .
      dockerfile: ./docker/zero-ui/Dockerfile
    restart: unless-stopped
    depends_on:
      - zerotier
    volumes:
      - ./zerotier-one:/var/lib/zerotier-one
      - ./data:/app/backend/data
    environment:
      - ZU_CONTROLLER_ENDPOINT=http://localhost:9993/
      - ZU_SECURE_HEADERS=true
      - ZU_DEFAULT_USERNAME=admin
      - ZU_DEFAULT_PASSWORD=zero-ui
    ports:
      - "4000:4000/tcp"

**Comment by aruznieto** [comment]
Try 

```
- ZU_CONTROLLER_ENDPOINT=http://zerotier:9993/
- ZU_SECURE_HEADERS=false
```

**Comment by v808comd** [comment]
Attempted
F12 can see the following prompt:
The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.

The page requested an origin-keyed agent cluster using the Origin-Agent-Cluster header, but could not be origin-keyed since the origin 'http://192.168.2.100:4000' had previously been placed in a site-keyed agent cluster. Update your headers to uniformly request origin-keying for all pages on the origin.

GET https://192.168.2.100:4000/app/assets/index-81542e93.css net::ERR_SSL_PROTOCOL_ERROR
GET https://192.168.2.100:4000/app/assets/index-ff38f170.js net::ERR_SSL_PROTOCOL_ERROR
GET https://192.168.2.100:4000/app/favicon.ico net::ERR_SSL_PROTOCOL_ERROR

**Comment by v808comd** [comment]
Looks like it's forced to use HTTPS

**Comment by aruznieto** [comment]
> Looks like it's forced to use HTTPS

It is strange, are you sure that your browser is no loading cache?

**Comment by v808comd** [comment]
Thank you, you are right. It's a cache issue

**Comment by aruznieto** [comment]
> Thank you, you are right. It's a cache issue

👍🏻

**Comment by dec0dOS** [comment]
Thanks for your support, @aruznieto!
Closing the issue.

**Comment by KweezyCode** [comment]
please reopen, issue still persists even with cache cleared, also tried on mobile - same issue
![image](https://github.com/user-attachments/assets/a9c9c3ec-d61f-4d78-9ea7-a694afbfc934)

**Comment by dec0dOS** [comment]
@KweezyCode you should set ZU_SECURE_HEADERS to false or use HTTPS in order to access the UI
