### ISSUE TITLE
bug: controller in the UI is presented as OFFLINE

### ISSUE THREAD

**Issue by knightian** [dec0dOS/zero-ui#31]
# Bug Report

**ZeroUI version:** latest

**Current behavior:**

When the controller is joined to a network, it is always showing in the UI as OFFLINE on that network

**Comment by knightian** [comment]
@dec0dOS re the nginx auth coz I can't comment on the other one, yea I got heaps of sites setup using basic auth the exact same way. there seems to be something in zero-ui that is perhaps stripping off the bearer or something so it thinks it's unauthorised? Only zero-ui does it.

**Comment by hamuraiisam** [comment]
I have the same issue. If I join the network with host client through docker exec, the first time it will work fine. But after a system restart the client shows offline and I get a PORT_ERROR under connection status

**Comment by kiam001** [comment]
Hi if you have 2 Zerotier clients (docker and Host) you need add in host zerotier conf folder from host a local.conf file with

```
{
    "settings": {
        "primaryPort": "9994"
    }
}
```

**Comment by dec0dOS** [comment]
Fixed in [v1.5.0](https://github.com/dec0dOS/zero-ui/commit/d6f05af126bd879da886ea23a42de995fcb22309).
