### ISSUE TITLE
bug: nginx basic auth enabled makes the UI go in an auth loop

### ISSUE THREAD

**Issue by knightian** [dec0dOS/zero-ui#32]
# Bug Report

**ZeroUI version:** latest

When I have the ui behind nginx reverse proxy and I enable basic auth, it just keeps asking for the credentials every request.

**Comment by dec0dOS** [comment]
This issue is not relevant to ZeroUI. That is the problem with your basic auth browser caching, and overall is related only to your setup.

**Comment by dec0dOS** [comment]
On the other hand, the problem may be in the Axios setup. Setting the `withCredentials: true` in options may help.

**Comment by knightian** [comment]
It's not a huge deal I have it behind oauth2-proxy now requiring AzureAD sign in, but worth mentioning nontheless

**Comment by dec0dOS** [comment]
Hello, @knightian 
The fix has been implemented in https://github.com/dec0dOS/zero-ui/commit/2396e973dc4e40f247cb5fef75d0403ccf0a285a
