### ISSUE TITLE
feat: capability and tags support

### ISSUE THREAD

**Issue by chenall** [dec0dOS/zero-ui#35]
# Feature Request

**Describe the Feature Request**

Not sure if the self-built controller supports these functions

**Additional Context**

![image](https://user-images.githubusercontent.com/628011/142798472-730e5210-fe56-468a-93dd-8ba59be6b932.png)
![image](https://user-images.githubusercontent.com/628011/142798508-8aa18a7e-6c55-4df2-b2d5-eb92ae1d8b43.png)

**Comment by timothyle97** [comment]
I agree that it would be nice to be able to change the node tags in the UI. Currently if you have the tags defined under your flow rules as your screenshot shows, you can use an API call to the controller to set the tags. 

This is an example of what I've used:
`curl -X POST 127.0.0.1:9993/api/network/xxxxxxxxxxxxxxxx/member/xxxxxxxxxx -H "X-ZT1-AUTH:xxxxxxxxxxxxxxxxxxxxxxxx" -d '{ "tags": [[1000,7],[1001,0]]}'`

The value after X-ZT1-AUTH is the API token of the ZT controller.

Reference for the controller API is here: [](https://my.zerotier.com/central-api.html#member-member-post)

**Comment by chenall** [comment]
@timothyle97 Yes, and zero-ui Flow rule currently does not support cap and tag, it will be ignored, there may be small bugs.

@dec0dOS 

e.g.

```
tag department
  id 1000 
  enum 100 sales
;

cap super
  id 1000
	accept;
;
```

![image](https://user-images.githubusercontent.com/628011/143367381-06d51ad5-309b-45ea-a96f-8524ffc0f339.png)

**Comment by timothyle97** [comment]
@chenall If I'm not mistaken the tags are implemented by the ZT controller, not Zero-UI. I believe if the tags are set on the network and the members via the API, any flow rules referencing the tags should work even though the preview shows the tags are empty. 

@dec0dOS I've found another project which acts as a command line interface to set the tags on the network and members for ZTNCUI: [https://github.com/Fusion/ztncli](https://github.com/Fusion/ztncli)

**Comment by snachx** [comment]
It's indeed a bug in zero-ui's flow rule editor which will ignore tags and caps, I've already fixed it but I haven't do a thoroughly test.

https://github.com/dec0dOS/zero-ui/blob/ee6a84e1a5339ba38fdb5880eaaef0297567be28/frontend/src/components/NetworkRules/NetworkRules.jsx#L54-L62

tags and caps should be object instead of array, the rule compiler uses them as objects to store parse result with names as keys.

**Comment by dec0dOS** [comment]
Hello, @snachx, thanks for sharing!

Please reach out to me if it works as expected for you.

**Comment by snachx** [comment]
@dec0dOS hello, you can check the detail of the rule compiler
https://github.com/dec0dOS/zero-ui/blob/ee6a84e1a5339ba38fdb5880eaaef0297567be28/frontend/src/external/RuleCompiler.js#L1042-L1047
https://github.com/dec0dOS/zero-ui/blob/ee6a84e1a5339ba38fdb5880eaaef0297567be28/frontend/src/external/RuleCompiler.js#L1120-L1124

the compile method uses caps and tags different from rules
rules have no names, they will be parsed and pushed to the rules array
both of tags and caps have names, and their names will be keys in the result objects

if we pass arrays as tags and caps, the spread syntax ...tags ...caps can't handle the result returned by the compile method.

I tried to init tags and caps as empty object and change the setFlowData method, it works as expected.

**Comment by snachx** [comment]
Also, even if the bug is fixed, the ui interface to set member's group and capabilities still needs to be developed, I've checked MemberSettings.jsx, there's no such support yet.

**Comment by dec0dOS** [comment]
Pull request https://github.com/dec0dOS/zero-ui/pull/41 has been merged to the main branch. This feature will be available with the new release.

Special gratitude goes to @snachx for finding the bug and developing the UI for tags and caps.
