### ISSUE TITLE
feat: Client last seen option

### ISSUE THREAD

**Issue by drtech981** [dec0dOS/zero-ui#40]
Instead of just showing if the client is online or not, it would be nice to have a last seen time for the client, which helps to diagnose certain issues such as power failure or hardware failure from a remote site (just as it shows in zerotier central manager).

**Comment by seanbts** [comment]
+1 for this feature, can help diagnose offline issues, knowing the time a node went offline.

**Comment by dec0dOS** [comment]
Hello, @drtech981. It is not easy to implement such a feature, as the controller API does not return the last seen member value. 
It would require consistent pinging from the server to the backend itself, and saving the "ONLINE" status. Current ZeroUI architecture would require some changes.

I agree that such a feature would be great for the user experience, so any help is welcome.

**Comment by timothyle97** [comment]
Yes, the controller API as currently available does not return this value. I have been trying to think about how to do this for a while, but haven't figured out a way yet. I will probably try to see if the ZeroTier implementation with the alternate database tracks online information.

**Comment by dec0dOS** [comment]
I've made some research on this topic.
If the Postgres database is used, the controller does save the last online time. But maintaining and building each version of the controller from source and adding the Postgres to the setup would require much effort.
ZeroUI is trying to be as efficient and as easy to install as possible.
I think that the better way to implement such a feature is the way as I said before.

For reference, see the https://github.com/zerotier/ZeroTierOne/blob/master/controller/LFDB.cpp

**Comment by timothyle97** [comment]
@dec0dOS I was wondering if you could give me a basic overview of how the frontend and backend services interact? I'm new to these programming languages and I was specifically wondering if any of the backend services run in the background, or if everything only runs when the admin web pages are loaded. Just trying to see what the options are with saving the online state of ZT clients.

**Comment by dec0dOS** [comment]
Hey, @timothyle97!
Check the following overview of the ZeroUI architecture:
Express server (backend) serves the frontend HTML/JS/CSS files (React-based application) to the user. 
Backend transforms the request from [ZeroTier Central API specification](https://my.zerotier.com/central-api.html) to the [controller API specification](https://docs.zerotier.com/service/v1/) and use the database to store and fetch the external data, that the controller itself does not store.

I see that there is two way to implement this feature: using the postgres controller build that already uses the [additional thread on the controller level to store the last online time data](https://github.com/zerotier/ZeroTierOne/blob/7ea2354540cd891f61d0944ff8a25c53a42bd038/controller/PostgreSQL.cpp#L237). But that approach have several downsides. 

So I think that the better way to implement this feature is to use the same technique on the backend level, not the controller level itself. Any nodejs recurring tasks scheduler should be okey for this task. To implement the following feature properly some backlog tasks should be done. Moving to the ES6 modules on the backend level, upgrading current dependencies, improving the developer experiance (using the vite build tool)

 
![Screenshot 2022-04-28 at 12 16 28](https://user-images.githubusercontent.com/14824142/165720326-45c8ec9f-dc78-46be-b94e-3ebbc4d0e418.png)

**Comment by dec0dOS** [comment]
Added in [v1.5](https://github.com/dec0dOS/zero-ui/commit/d6f05af126bd879da886ea23a42de995fcb22309).
