### ISSUE TITLE
bug: Clients being shown offline when they are online

### ISSUE THREAD

**Issue by drtech981** [dec0dOS/zero-ui#42]
Many clients are being shown offline when they are actually online

`zerotier-cli peers
`
shows the intended clients as online. Same client on ztncui is also shown as online.

**Comment by dec0dOS** [comment]
Hello, @drtech981. It seems strange. `peerData.online` maybe should be parsed another way. What type of clients does showing incorrectly?

**Comment by drtech981** [comment]
Clients are Windows and Linux clients running various versions of Zerotier : 
![image](https://user-images.githubusercontent.com/79300765/145872325-d90962ac-48ce-4806-838f-78fd4a9b92e7.png)
Clients on ZTNCUI
![image](https://user-images.githubusercontent.com/79300765/145872360-aaee109f-9f28-4dfa-a53a-d9c28eaf3d52.png)
Clients in ZERO-UI
![image](https://user-images.githubusercontent.com/79300765/145872433-7c1f7e36-e2d3-4bfd-93fc-127e49eb175f.png)
from zu-controller> zerotier-cli listpeers
![image](https://user-images.githubusercontent.com/79300765/145872570-a6a9b305-09ad-4f05-800f-e55278980867.png)
Pinging the peers confirms that it is infact UP and online.

**Comment by timothyle97** [comment]
As shown in the screenshot by @drtech981, peers that are currently connected to the controller are shown in the list when the listpeers or peers command is issued (as well as an API call). If the peer has a direct connection to the controller, there will be a valid latency value. If the peer is relayed, the latency is -1. If the peer is offline, it will not show up in the list.

**Comment by dec0dOS** [comment]
Fixed in https://github.com/dec0dOS/zero-ui/commit/504ce7f4b13309b5ea33a8efe0bad530ad77958b.
Thanks @timothyle97!
