### ISSUE TITLE
feat: Client connecting IP and Port

### ISSUE THREAD

**Issue by drtech981** [dec0dOS/zero-ui#43]
Would be better if a member's real connecting IP and port is displayed in addition to OFFLINE/ONLINE status (like shown in ztncui).

Extremely helpful in diagnosing connectivity and latency issues.

![SmartSelect_20211213-154907_Chrome](https://user-images.githubusercontent.com/79300765/145794503-4ae8cca0-20fa-4f92-ae4a-9a3e4b2ee6fb.jpg)

**Comment by dec0dOS** [comment]
@drtech981, thank you for report. It has been on the private feature list for a while.

**Comment by dec0dOS** [comment]
Added in https://github.com/dec0dOS/zero-ui/commit/504ce7f4b13309b5ea33a8efe0bad530ad77958b.
Thanks @timothyle97!
