### ISSUE TITLE
feat: hosting without Docker/Podman

### ISSUE THREAD

**Issue by cyagon** [dec0dOS/zero-ui#51]
# Feature Request

**Describe the Feature Request**

The possibility to host zero-ui without a container-solution like Podman or Docker, like ztncui has. This would allow hosting of controllers even on very tiny NAT-vps like the https://natvps.net "NAT256" offerings. The update-process could then work with apt/rpm packages like ztncui does here: https://github.com/key-networks/ztncui/blob/master/build/build.sh or just a bash-script that pulls the changes from the latest git-release.

**Comment by 9p4** [comment]
It's fairly simple to do without containers. Run `node ./bin/www` from the backend directory to serve the API and use Nginx or Apache to serve the frontend and proxy connections to the backend.

When running the node process make sure that the correct environment vars are set:

```
NODE_ENV=production
ZU_SERVE_FRONTEND=false
ZU_SECURE_HEADERS=true
ZU_CONTROLLER_ENDPOINT=http://localhost:9993
ZU_CONTROLLER_TOKEN=secret
ZU_DEFAULT_USERNAME=username
ZU_DEFAULT_PASSWORD=password
```

Here's an example for Apache (assuming that the frontend was built and placed in `/zero-ui/public`.

```
ServerName ztui.example.com
ProxyPass "/app" !
ProxyPass "/" "http://localhost:4000/"

Alias /app /zero-ui/public

ErrorDocument 401 'Sign-in failed. Are you allowed access?'

OIDCSessionInactivityTimeout 10

<Location /app>
	FallbackResource /app/index.html
</Location>
```
