### ISSUE TITLE
dev: hosting the web-ui without root

### ISSUE THREAD

**Issue by cyagon** [dec0dOS/zero-ui#52]
Currently, zero-ui hosts its web-interface with root privileges. There should be an option to host its processes without it.
When it comes to container-hosting, ztncui achieved this by giving the web-ui an own user inside the Dockerfile (https://github.com/key-networks/ztncui-aio/blob/79a389244cb1195ec4e01218800a7fb288ae82ff/Dockerfile#L51), then starting the process via https://github.com/tianon/gosu (https://github.com/key-networks/ztncui-aio/blob/79a389244cb1195ec4e01218800a7fb288ae82ff/start_ztncui.sh#L66).

Alternatively, vaultwardens docker-image makes this possible via dockers "-u" command: https://github.com/dani-garcia/vaultwarden/wiki/Hardening-Guide#run-as-a-non-root-user

**Comment by 9p4** [comment]
IMO this is a shortcoming of Docker itself, not really ZeroUI. Running with [Podman](https://podman.io) as a non-root user might be a better deployment strategy if you're concerned about root escapes.
