### ISSUE TITLE
bug: UI crashes when a network contains no IP ranges

### ISSUE THREAD

**Issue by voobscout** [dec0dOS/zero-ui#58]
# Bug Report

**ZeroUI version:**
latest

**Current behavior:**
```Cannot read properties of undefined (reading 'ipRangeStart')```

**Expected behavior:**
should be no problem to manage a network without ip assignments, ie, managing ips with kea-dhcp bridged to zerotier

**Steps to reproduce:**
create a new network, remove ip ranges and try to login/logout

**Comment by dec0dOS** [comment]
Fixed in https://github.com/dec0dOS/zero-ui/pull/71

Thanks, @BrianWieder.
