### ISSUE TITLE
feat: ref to zyclonite/zerotier in docker-compose

### ISSUE THREAD

**Issue by maltegrosse** [dec0dOS/zero-ui#66]
# Feature Request

**Describe the Feature Request**

as https://hub.docker.com/r/dec0dos/zerotier-controller is quite outdated, perhaps its easier to just refer to latest `zyclonite/zerotier`
**Describe Preferred Solution**
refer to in
https://github.com/dec0dOS/zero-ui/blob/main/docker-compose.yml#L5
to `zyclonite/zerotier`

**Comment by dec0dOS** [comment]
Implemented in https://github.com/dec0dOS/zero-ui/commit/04624d13c8451c68d4d4c673a577b14e6172ceb8
