### ISSUE TITLE
dev:  Add try/catch in zt-address.js

### ISSUE THREAD

**Issue by roxlu** [dec0dOS/zero-ui#87]
When the `api.get.status()` call fails in `zt-address.js` you get a unhandled promise rejection error w/o a stacktrace. 

Adding try/catch + log will give a bit more info: 

```js
const api = require("../utils/controller-api");

module.exports = async function () {
  try {
    const res = await api.get("status");
    return res.data.address;
  }
  catch (err) {
    console.error(err);
  }
};

```

**Comment by dec0dOS** [comment]
Hello, @roxlu.
Thanks for your suggestion. Implemented in https://github.com/dec0dOS/zero-ui/commit/d7f2e153286f9e1dacf4d9fa993321fd6fbc3836
