### ISSUE TITLE
bug: docker up fails due to "no-build" flag

### ISSUE THREAD

**Issue by Ifiht** [dec0dOS/zero-ui#88]
# Bug Report

**ZeroUI version:**

3.3, latest

**Current behavior:**

Following the instructions exactly as written, on ubuntu 20.04 results in:
```
sudo docker-compose up -d --no-build
Pulling zerotier    ... done
Pulling https-proxy ... done
ERROR: Service 'zero-ui' needs to be built, but --no-build was passed.
```
Eliminating the flag fails as well:
```
sudo  docker-compose up -d
Building zero-ui
ERROR: Cannot locate specified Dockerfile: ./docker/zero-ui/Dockerfile
```

**Expected behavior:**

Should work, start the docker container.

**Steps to reproduce:**

Fresh install of Ubuntu 20.04, follow the steps in the readme.

**Comment by HaganMSP** [comment]
I am having the same issue on my Digital Ocean droplet. All updates, latest Docker/Compose etc.

> #docker-compose pull
> Pulling zerotier    ... done
> Pulling https-proxy ... done

># docker-compose up -d --no-build
> ERROR: Service 'zero-ui' needs to be built, but --no-build was passed.

> #docker-compose up
> Building zero-ui
> ERROR: Cannot locate specified Dockerfile: ./docker/zero-ui/Dockerfile

**Comment by dec0dOS** [comment]
Seems to be that it's the docker/docker-compose bug on some systems. Could you try the `docker pull dec0dos/zero-ui` and then `docker-compose up -d --no-build`?

**Comment by HaganMSP** [comment]
![image](https://user-images.githubusercontent.com/108075066/175972215-fb55bef2-cc10-48b4-9fa2-4dd2e5ad69fe.png)

That works, thank you.

**Comment by dec0dOS** [comment]
@HaganMSP, thanks for the report, I'll update the README.md with the `docker pull` command instead.
